### ISSUE TITLE
AttributeError when use reproject

### ISSUE THREAD

**Issue by HrsPythonix** [dlr-eoc/camera#1]
\>>> Q = mycam.reproject(p)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "camera/__init__.py", line 164, in reproject
    Xi = self.Si.dot(self.__Kinv__()).dot(self.Pi).dot(X3d)
AttributeError: 'Camera' object has no attribute 'Si'

**Comment by HrsPythonix** [comment]
And it seems that you haven't use the distance in reprojection.

**Comment by EasyIsrael** [comment]
Hi HrsPythonix,
thanks for your comment.  It seems that my documentation is still not finished.
i will change that soon.

you need to set the transformation matrix via the method 
attitudeMat(mat)

a working example is  here:

```
import numpy as np
import camera
P = np.array([[1],[0],[10],[1]])
mycam = camera.Camera()
mycam.intrinsics(640,512,1000,320,260)
p = mycam.project(P)
mycam.attitudeMat(np.eye(4))
print ("projection:",p)
q = mycam.reproject(p)
print ("reprojection at distance 1:",q)
```

**Comment by HrsPythonix** [comment]
Thanks for your quick reply, but I wonder why the reprojection result is:
```
array([[0.04997501],
       [0.        ],
       [0.49975012],
       [1.        ]])
```
but not:
```
np.array([[1],[0],[10],[1]])
```

Although I understand that these two point are on the same line, I just ask this for curiosity.

**Comment by EasyIsrael** [comment]
oh thanks, 
now i see the bug you mentioned with the distance!

i will fix that quickly. And write again, when i am finished.

**Comment by HrsPythonix** [comment]
Okay, please let me know once you finish~

BTW, I planned to make an interesting application based on your repo, if you don't mind.

**Comment by EasyIsrael** [comment]
that sounds great. 
for real application the most important thing for this lib seems to be the brown - model for real lenses.
This is still work in process. but will be implemented soon.

for best performance i want to implement a look up table for each pixel. then you can model best all kinds of errors a camera brings with.
  
what kind of software are you programming?

**Comment by HrsPythonix** [comment]
I plan to do automatic parallax effect on single image,  much like a camera moving in a scene. But I got caught in the camera projection and reprojection step, until I found your repo.

**Comment by EasyIsrael** [comment]
ah nice,
then you don't need any real world camera lens correction stuff.
you can use simply the pinhole model.

**Comment by HrsPythonix** [comment]
Exactly as you say~

**Comment by EasyIsrael** [comment]
but you need additional information about near and far regions in your image. How do you do that?

**Comment by HrsPythonix** [comment]
There are a lot of methods to do that now, to retrieve depth info from 2D RGB image. 

For example, https://github.com/mrharicot/monodepth

Since I do not need the depth info to be very precise, this is enough for me to generate a parallax effect.

**Comment by EasyIsrael** [comment]
wow, that's great stuff
thank's for the link. very impressive!

**Comment by EasyIsrael** [comment]
now i  know the problem:

i have redesigned my library to be able to use it in other projects.

the "distance"-parameter makes no sense in this method.
 
reprojection is designed to just give back an orientation vector in homogenious coordinates.

what you need is a wrapper around reprojection, that gives you a reprojection with world coordinates.

in my application i have a function where i put pixel coordinates in and get back the world coordinates as UTM coordinates .
  
the problem is, you need something to reproject the pixels on. therefore you have to 
set a plane in your space and use the camera position and the reprojection vector and let the ray 
intersect the plane.
in your case i think it makes sense to let the plane be parallel to the camera focal plane array.
then you could use simply a distance.
i'm now implementing something based on that, because many could find it useful to have such a method.

if you are in a hurry you could look how i implemented it in my software:

```
class Mycam(Camera):
    
    def ray_intersect_plane(self,raypos, raydir, plane, front_only=True):
        """Calculates the intersection point of a ray and a plane.

        :param numpy.array ray: The ray to test for intersection.
        :param numpy.array plane: The ray to test for intersection.
        :param boolean front_only: Specifies if the ray should
        only hit the front of the plane.
        Collisions from the rear of the plane will be
        ignored.

        :return The intersection point, or None
        if the ray is parallel to the plane.
        Returns None if the ray intersects the back
        of the plane and front_only is True.
        """
        """
        Distance to plane is defined as
        t = (pd - p0.n) / rd.n
        where:
        rd is the ray direction
        pd is the point on plane . plane normal
        p0 is the ray position
        n is the plane normal

        if rd.n == 0, the ray is parallel to the
        plane.
        >>> a = np.array([[4.],[0.],[5.]])
        >>> b = np.array([[0.],[2.],[-3.]])
        >>> plane = np.array([0.,0.,1.,0.])
        >>> erg =  ray_intersect_plane(a,b,plane)
        >>> print erg
        [[ 4.        ]
        [ 3.33333333]
        [ 0.        ]]

        """
        p = plane[:3] * plane[3]
        n = plane[:3]
        rd_n = np.dot(raydir.ravel(), n)
        if rd_n == 0.0:
            return np.array([[None],[None],[None]])

        if front_only == True:
            if rd_n >= 0.0:
                return np.array([[None],[None],[None]])

        pd = np.dot(p, n)
        p0_n = np.dot(raypos.ravel(), n)
        t = (pd - p0_n) / rd_n
        return raypos + (raydir * t)

    def poi(self,x,y,ele=0):
        if self.distortionmodel == CamModel.NOCAM:
            raise("Error- with NOCAM this method doeas not work!")
        poi_cam = np.array([[x],[y],[1],[1]])
        rp = self.reproject(poi_cam)
        campos = self.position()
        raydir = rp - campos
        poi = self.ray_intersect_plane(campos[0:3],raydir[0:3],np.array([0,0,1,ele]))
        return poi
```

**Comment by EasyIsrael** [comment]
a solution for this is implemented as  reprojectToPlane() in the new version 0.31

**Comment by HrsPythonix** [comment]
Seem that your `project` function support project multi-points at the same time, but the `reprojection` does not.

```
>>> P = np.array([[[14],[0],[1000],[1]], [[7],[0],[1000],[1]]])
>>> P
array([[[  14],
        [   0],
        [1000],
        [   1]],

       [[   7],
        [   0],
        [1000],
        [   1]]])
>>> P.shape
(2, 4, 1)
>>> p = mycam.project(P).T
>>> p
array([[[334., 260.],
        [327., 260.]]])
>>> p.shape
(1, 2, 2)
>>> mycam.reproject(p)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "camera/__init__.py", line 163, in reproject
    """
IndexError: index 1 is out of bounds for axis 0 with size 1
>>> mycam.reproject(p.T)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "camera/__init__.py", line 164, in reproject
    if self.distortionmodel == CamModel.NOCAM:
ValueError: shapes (4,4) and (4,2,1) not aligned: 4 (dim 1) != 2 (dim 1)
>>> mycam.reproject(p.T[0])
array([[0.0069965 ],
       [0.03348326],
       [0.49975012],
       [1.        ]])
>>> mycam.reproject(p.T[1])
array([[-0.02998501],
       [ 0.        ],
       [ 0.49975012],
       [ 1.        ]])
```

Any idea?
