### ISSUE TITLE
Multiple point reprojection

### ISSUE THREAD

**Issue by EasyIsrael** [dlr-eoc/camera#2]
Seem that your `project` function support project multi-points at the same time, but the `reprojection` does not.
```
>>> P = np.array([[[14],[0],[1000],[1]], [[7],[0],[1000],[1]]])
>>> P
array([[[  14],
        [   0],
        [1000],
        [   1]],

       [[   7],
        [   0],
        [1000],
        [   1]]])
>>> P.shape
(2, 4, 1)
>>> p = mycam.project(P).T
>>> p
array([[[334., 260.],
        [327., 260.]]])
>>> p.shape
(1, 2, 2)
>>> mycam.reproject(p)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "camera/__init__.py", line 163, in reproject
    """
IndexError: index 1 is out of bounds for axis 0 with size 1
>>> mycam.reproject(p.T)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "camera/__init__.py", line 164, in reproject
    if self.distortionmodel == CamModel.NOCAM:
ValueError: shapes (4,4) and (4,2,1) not aligned: 4 (dim 1) != 2 (dim 1)
>>> mycam.reproject(p.T[0])
array([[0.0069965 ],
       [0.03348326],
       [0.49975012],
       [1.        ]])
>>> mycam.reproject(p.T[1])
array([[-0.02998501],
       [ 0.        ],
       [ 0.49975012],
       [ 1.        ]])
```

Any idea?

_Originally posted by @HrsPythonix in https://github.com/dlr-eoc/camera/issues/1#issuecomment-443095037_

**Comment by EasyIsrael** [comment]
thanks!
good point. i will change that.  

maybe it would be useful to allow different types of datarepresentations.
currently you have to put column vectors, but usually pixelpositions come as 1-Dim tuple or a flat numpy array.

i'm concerning about performance.
If you try to map the whole image pixelwise, it could take a while.
But even if you do it with just one call, it will be not very fast.
we should make a performance test.

**Comment by HrsPythonix** [comment]
For now, I have to iterate every pixel in my image, reproject them to world , change their depth(move forward) and project back to the image, it is very slow when you do this pixel by pixel.

I am wondering if you can modify the `reproject` function to make it as fast as `project`.

I think the `project` is doing some matrix multiplication, and numpy is optimized for this, which means I can speed up a lot if I fed multi-point into the function. I hope the `reproject` can do like that too.

**Comment by EasyIsrael** [comment]
Okay, i've done it in version 0.32.

now multiple points are supported.

here is an example that i used for testing:
```
>>>import numpy as np
>>>import camera
>>>cam = camera.Camera()
>>>cam.intrinsics(640,512,1000,320,256)
>>>cam.attitudeMat(np.eye(4))
>>>P1 = np.array([[1],[0],[10],[1]])
>>>P2 = np.array([1,0,10,1])
>>>P = np.array([[2,0,10],[1,0,10],[0,0,10],[-1,0,10]])

*****SINGE PROJECTION*****

>>>p2 = cam.project(P2)
>>>print ("row vector:",P2)
row vector: [ 1  0 10  1]
>>>print ("projection:",p2)
projection: [420. 256.]
>>>Q2 = cam.reproject(p2)
>>>p1 = cam.project(P1)
>>>print ("column vector:",P1)
column vector: [[ 1]
 [ 0]
 [10]
 [ 1]]
>>>print ("projection:",p1)
projection: [420. 256.]
>>>Q1 = cam.reproject(p1)
>>>print ("reprojection:",Q1)
reprojection: [0.04997501 0.         0.49975012 1.        ]
>>>Q1w = cam.reprojectToPlane(p1,10)
>>>print ("reprojectionToPlane:",Q1w)
reprojectionToPlane: [ 1.  0. 10.]

*****MULTIPLE PROJECTION*****

>>>p = cam.project(P)
>>>print (P)
[[ 2  0 10]
 [ 1  0 10]
 [ 0  0 10]
 [-1  0 10]]
>>>print ("projection:",p)
projection: [[520. 256.]
 [420. 256.]
 [320. 256.]
 [220. 256.]]
>>>Q = cam.reproject(p)
>>>print ("reprojection:",Q)
reprojection: [[ 0.09995002  0.          0.49975012  1.        ]
 [ 0.04997501  0.          0.49975012  1.        ]
 [ 0.          0.          0.49975012  1.        ]
 [-0.04997501  0.          0.49975012  1.        ]]
>>>Q2 = cam.reprojectToPlane(p,10)
>>>print ("reprojection:",Q2)
reprojection: [[ 2.  0. 10.]
 [ 1.  0. 10.]
 [ 0.  0. 10.]
 [-1.  0. 10.]]
```

**Comment by HrsPythonix** [comment]
One more question, what is your length unit in numpy array, mm or cm or m or?

**Comment by EasyIsrael** [comment]
oh sorry, i missed your question.

it's up to you, but you have to be consistent. 

normally you use pixels for the intrinsic parameters and meter for the external parameter.

when you set the intrinsics, these values are all pixel values. 

```cam.intrinsics(640,512,1000,320,256)```
the third parameter is focallength. This is a bit confusing to set this value in amount of pixels, but you can easily translate this from mm to pixels, when you know the size of one pixel.
E.g. you have a camera with a lens with focal length 19 mm and a  detector (focal plane array) with pixelsize of 17 um, then the corresponding fx in pixel  is 1117.64 

with this parameter you influence if your camera has a fisheye lense or a telephoto lens or something in between.

the extrinsic parameters are set by your (4x4) attitudeMatrix.
the first 3 columns describe the (extrinsic) rotation of your camera. its a simple rotation matrix.
the 4th column describes the translation from your world coordinate origin.

when this value is in m, all other 3D-world parameter are also in meter.

i hope this helps you a bit. 
the documentation at this point is not finished yet.
